### ISSUE TITLE
Property 'React' does not exist

### ISSUE THREAD

**Issue by sapkra** [50UM3N/tabler-icons-react-native#2]
I've just imported an icon into my project and I'm getting the following error. The best solution would be to import React in all component files, I guess.

<img width="385" alt="image" src="https://user-images.githubusercontent.com/8087568/199037545-65970fb2-cb81-4600-a139-0273c89782dd.png">

**Comment by 50UM3N** [comment]
> I've just imported an icon into my project and I'm getting the following error. The best solution would be to import React in all component files, I guess.
> 
> <img alt="image" width="385" src="https://user-images.githubusercontent.com/8087568/199037545-65970fb2-cb81-4600-a139-0273c89782dd.png">

I guess you are using React, This library is compatible with react native. Try to use https://www.npmjs.com/package/@tabler/icons for React.

**Comment by sapkra** [comment]
React is the shared layer of react-native and react-dom, as I know. So both are using React. I'm just using the official react native typescript template.

I was able to solve it somehow starting metro with `yarn start --reset-cache`.

**Comment by 50UM3N** [comment]
Just install `react-native-svg` then check.

**Comment by 50UM3N** [comment]
> React is the shared layer of react-native and react-dom, as I know. So both are using React. I'm just using the official react native typescript template.
> 
> I was able to solve it somehow starting metro with `yarn start --reset-cache`.

Actually native SVG tags that are supported in the browser do not natively support in react native so we need an extra library `react-native-svg` to do that.

**Comment by sapkra** [comment]
It was already installed in my project. Like I said, it's working now, after I cleared the cache.
